### ISSUE TITLE
Config Template Blocked by Safe Mode

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest_docs#26]
There is not a whole lot that needs to be said about this. We probably do not want to run the production server in `unsafe` mode, but the next level up, `safe` mode, does not permit accessing ancestor directories of the document.

Edit: We can specify a base directory for the conversion, but we get this warning when doing so: `asciidoctor: WARNING: include file has illegal reference to ancestor of jail; recovering automatically`

**Comment by benrob0329** [comment]
In order to make this work in safe mode, we'd have to move the `include` directory into the `docs` directory, and have all of our doc sources in the same directory. I don't think that's worth it, especially since the whole thing is public and pretty easily verifiable anyways.

The only other alternative I can think of is to abuse symlinks, but that seems worse.

**Comment by JosiahWI** [comment]
That makes sense. We must ensure that changes to the documentation can not be made without developer review, with that approach, but I think that was our plan anyway.
