### ISSUE TITLE
Update note about texture modifier memleaks

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest_docs#48]
Verify that https://github.com/minetest/minetest/pull/12514 fixes texture modifier memleaks (does it?)

**Comment by 20kdc** [comment]
It doesn't fix texture modifier leaks. The original version of the PR, before the change in direction, was part of a comprehensive solution to deal with leaks caused by the server having to use different paths for new uploaded images (thus slowly flooding the client modifier cache). Think "MineClone maps" if you want an idea of what could cause this.

**Comment by appgurueu** [comment]
Alright, thanks for clarifying!
